### ISSUE TITLE
Avisos Tecnologías emergentes

### ISSUE THREAD

**Issue by mjtenmat** [mjtenmat/ATHENA#14]
Se están generando avisos únicamente de Documentos Académicos, se han perdido las búsquedas automáticas de Patentes, Licitaciones y Documentos Web. Debemos recuperar las búsquedas automáticas de estas otras tipologías documentales.

Por otro lado, cuando establecemos un término principal y unos relacionados, las coincidencias que se encuentren en la búsqueda de términos relacionados deberían aparecer en el panel de avisos de tecnologías emergentes bajo el término principal como "encabezamiento", y lo están haciendo bajo los secundarios.

Por ejemplo:
Término principal: energía solar -> Términos secundarios: solar photovoltaica, solar térmica, solar energy, photovoltaics, solar PV, thermal energy.

Los resultados obtenidos de las búsquedas efectuadas con los términos secundarios, (por ejemplo: búsqueda: "photovoltaics") deberían reflejarse así:

**Avisos:**
**## Energía solar:**
- Patente: procedé de construction de membrane.....
30-may-2017.
Resumen.

Y no como lo hace ahora:
**Avisos:**
**## Photovoltaic:**
- Patente: procedé de construction de membrane.....
30-may-2017.
Resumen.

**Comment by mjaque** [comment]
He ejecutado el Vigilante de Tendencias y no ha habido ningún error. Ha encontrado avisos de patentes.

Dime el aviso que has registrado y el resultado que debería dar.
